
namespace ScientificResearch.Utility.Enums
{
    public enum ApplicationSortField
    {
        ID = 0,
        WorkName,
        WenHao,
        FormID,
        WorkFlowID,
        UserName,
        TimeStr,
        FormContent,
        FuJianList,
        ShenPiYiJian,
        JieDianID,
        JieDianName,
        ShenPiUserList,
        OKUserList,
        StateNow,
        LateTime,
        BeiYong1,
        BeiYong2,
        ApplicationStatus,
        ApplicationId,
        FormKeys,
        FormValues,

        ID_Desc,
        WorkName_Desc,
        WenHao_Desc,
        FormID_Desc,
        WorkFlowID_Desc,
        UserName_Desc,
        TimeStr_Desc,
        FormContent_Desc,
        FuJianList_Desc,
        ShenPiYiJian_Desc,
        JieDianID_Desc,
        JieDianName_Desc,
        ShenPiUserList_Desc,
        OKUserList_Desc,
        StateNow_Desc,
        LateTime_Desc,
        BeiYong1_Desc,
        BeiYong2_Desc,
        ApplicationStatus_Desc,
        ApplicationId_Desc,
        FormKeys_Desc,
        FormValues_Desc,
    }
}