//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBBSBanKuai
    {
        public int ID { get; set; }
        public string BanKuaiName { get; set; }
        public string BanZhuList { get; set; }
        public string BanKuaiMiaoShu { get; set; }
        public string BanKuaiImg { get; set; }
        public string JiaoSeXianZhiList { get; set; }
        public string BuMenXianZhi { get; set; }
        public string UserXianZhi { get; set; }
    }
}
