//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBuyOrder
    {
        public int ID { get; set; }
        public string OrderName { get; set; }
        public string GongYingShangName { get; set; }
        public string Serils { get; set; }
        public string DingDanLeiXing { get; set; }
        public string DingDanMiaoShu { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LaiHuoDate { get; set; }
        public Nullable<System.DateTime> TiXingDate { get; set; }
        public string ChuangJianRen { get; set; }
        public string FuZeRen { get; set; }
        public string FuJianList { get; set; }
        public string NowState { get; set; }
        public string ShenPiTongGuoRen { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public Nullable<double> HTZJ { get; set; }
        public Nullable<double> YFFY { get; set; }
        public string SFJF { get; set; }
        public Nullable<double> SQFY { get; set; }
    }
}
