//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBBSTieZi
    {
        public int ID { get; set; }
        public Nullable<int> BanKuaiID { get; set; }
        public string TitleStr { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string ContentStr { get; set; }
        public string ZuiHouUser { get; set; }
        public Nullable<System.DateTime> ZuiHouTime { get; set; }
        public Nullable<int> PaiXu { get; set; }
        public string HuiFuContent { get; set; }
    }
}
