//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBaoJia
    {
        public int ID { get; set; }
        public string CustomName { get; set; }
        public string BaoJiaTitle { get; set; }
        public string BaoJiaType { get; set; }
        public string BaoJiaJinE { get; set; }
        public string BaoJiaContent { get; set; }
        public string BaoJiaResult { get; set; }
        public string BaoJiaTime { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFShare { get; set; }
        public string CusBakA { get; set; }
        public string CusBakB { get; set; }
        public string CusBakC { get; set; }
        public string CusBakD { get; set; }
        public string CusBakE { get; set; }
    }
}
