//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBuyOrder
    {
        public int ID { get; set; }
        public string OrderName { get; set; }
        public string GongYingShangName { get; set; }
        public string Serils { get; set; }
        public string DingDanLeiXing { get; set; }
        public string DingDanMiaoShu { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LaiHuoDate { get; set; }
        public Nullable<System.DateTime> TiXingDate { get; set; }
        public string ChuangJianRen { get; set; }
        public string FuZeRen { get; set; }
        public string FuJianList { get; set; }
        public string NowState { get; set; }
        public string ShenPiTongGuoRen { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public Nullable<double> HTZJ { get; set; }
        public Nullable<double> YFFY { get; set; }
        public string SFJF { get; set; }
        public Nullable<double> SQFY { get; set; }
    }
}
