//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBuyChanPin
    {
        public int ID { get; set; }
        public string OrderName { get; set; }
        public string ProductName { get; set; }
        public string ProductSerils { get; set; }
        public string GongYingShang { get; set; }
        public string ProductType { get; set; }
        public string XingHao { get; set; }
        public string DanWei { get; set; }
        public Nullable<decimal> DanJia { get; set; }
        public Nullable<decimal> ShuLiang { get; set; }
        public Nullable<decimal> ZongJia { get; set; }
        public Nullable<decimal> YiFuKuan { get; set; }
        public Nullable<decimal> QianKuanShu { get; set; }
        public string IFJiaoFu { get; set; }
        public string ChanPinMiaoShu { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
