//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBBSBanKuai
    {
        public int ID { get; set; }
        public string BanKuaiName { get; set; }
        public string BanZhuList { get; set; }
        public string BanKuaiMiaoShu { get; set; }
        public string BanKuaiImg { get; set; }
        public string JiaoSeXianZhiList { get; set; }
        public string BuMenXianZhi { get; set; }
        public string UserXianZhi { get; set; }
    }
}
