//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBuMen
    {
        public int ID { get; set; }
        public string BuMenName { get; set; }
        public string ChargeMan { get; set; }
        public string TelStr { get; set; }
        public string ChuanZhen { get; set; }
        public string BackInfo { get; set; }
        public Nullable<int> DirID { get; set; }
    }
}
