//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBaoXiao
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string FeiYongType { get; set; }
        public string ShenQingRen { get; set; }
        public string ShenPiRen { get; set; }
        public string ShenQingContent { get; set; }
        public string JinE { get; set; }
        public string StateNow { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ShenQingTime { get; set; }
    }
}
