//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBaoXiao
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string FeiYongType { get; set; }
        public string ShenQingRen { get; set; }
        public string ShenPiRen { get; set; }
        public string ShenQingContent { get; set; }
        public string JinE { get; set; }
        public string StateNow { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ShenQingTime { get; set; }
    }
}
