//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBuyChanPin
    {
        public int ID { get; set; }
        public string OrderName { get; set; }
        public string ProductName { get; set; }
        public string ProductSerils { get; set; }
        public string GongYingShang { get; set; }
        public string ProductType { get; set; }
        public string XingHao { get; set; }
        public string DanWei { get; set; }
        public Nullable<decimal> DanJia { get; set; }
        public Nullable<decimal> ShuLiang { get; set; }
        public Nullable<decimal> ZongJia { get; set; }
        public Nullable<decimal> YiFuKuan { get; set; }
        public Nullable<decimal> QianKuanShu { get; set; }
        public string IFJiaoFu { get; set; }
        public string ChanPinMiaoShu { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
