//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPBook
    {
        public int ID { get; set; }
        public string BookName { get; set; }
        public string BookSerils { get; set; }
        public string SuoShuBuMen { get; set; }
        public string BookType { get; set; }
        public string Auother { get; set; }
        public string ISBN { get; set; }
        public string CoperStr { get; set; }
        public string ChuBanDate { get; set; }
        public string CunFangDian { get; set; }
        public string ShuLiang { get; set; }
        public string JiaGe { get; set; }
        public string NeiRong { get; set; }
        public string NowState { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
