//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCommon
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string CName { get; set; }
        public string CType { get; set; }
        public int CSort { get; set; }
        public string CDescription { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
