//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCustomInfo
    {
        public int ID { get; set; }
        public string CustomName { get; set; }
        public string CustomSerils { get; set; }
        public string ChargeMan { get; set; }
        public string Address { get; set; }
        public string UrlLink { get; set; }
        public string YouBian { get; set; }
        public string TelStr { get; set; }
        public string XingZhi { get; set; }
        public string LaiYuan { get; set; }
        public string QuYu { get; set; }
        public string ZhuangTai { get; set; }
        public string RenShu { get; set; }
        public string BanGongMianJi { get; set; }
        public string LeiBie { get; set; }
        public string JiBie { get; set; }
        public string YeWuFanWei { get; set; }
        public string HangYe { get; set; }
        public string MuQianWenTi { get; set; }
        public string YuJiDingDanDate { get; set; }
        public string BackInfoA { get; set; }
        public string BackInfoB { get; set; }
        public string BackInfoC { get; set; }
        public string BackInfoD { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string UserName { get; set; }
        public string DingDanCount { get; set; }
        public string YuJiTiXing { get; set; }
        public string IFShare { get; set; }
        public string CusBakA { get; set; }
        public string CusBakB { get; set; }
        public string CusBakC { get; set; }
        public string CusBakD { get; set; }
        public string CusBakE { get; set; }
        public string NameEng { get; set; }
        public string FaRenDaiMa { get; set; }
        public string YingYeZhiZhao { get; set; }
        public string ZiBenE { get; set; }
        public string ZuZhiXingZhi { get; set; }
        public string YingYeChangSuo { get; set; }
        public string JingJi { get; set; }
        public string SheHuiGuanXi { get; set; }
        public string BenGongSiGuanXi { get; set; }
        public string JieShaoRen { get; set; }
        public string BaoZhengRen { get; set; }
        public string ShuiPiaoName { get; set; }
        public string DiZhiDianHua { get; set; }
        public string NaShuiDengJiHao { get; set; }
        public string KaiHuHangZhangHao { get; set; }
        public string JiaoYiFangShi { get; set; }
        public string ZhangQi { get; set; }
        public string FuKuanFangShi { get; set; }
        public string YunFeiChengDan { get; set; }
        public string CuXiaoFei { get; set; }
        public string GuangGaoFei { get; set; }
        public string YouDaiZheKou { get; set; }
        public string FuKuanTaiDu { get; set; }
        public string ShiFouDuiZhang { get; set; }
        public string DuiZhangShiJian { get; set; }
        public string ZuiJiaPaiFangShiJian { get; set; }
        public string ZuiJiaShouKuanShiJian { get; set; }
        public string QiTaGongYing { get; set; }
        public string ChangYongNaJia { get; set; }
        public string GongSiYiJian { get; set; }
        public string ZiXin { get; set; }
        public string ZongJieLun { get; set; }
    }
}
