//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCustomNeed
    {
        public int ID { get; set; }
        public string CustomName { get; set; }
        public string NeedContent { get; set; }
        public string NeedNow { get; set; }
        public string NeedProduct { get; set; }
        public string NeedTime { get; set; }
        public string NeedLike { get; set; }
        public string JingZhengDuiShou { get; set; }
        public string HeZuoYiYuan { get; set; }
        public string HeZuoJiLv { get; set; }
        public string NeedZhangAi { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFShare { get; set; }
        public string CusBakA { get; set; }
        public string CusBakB { get; set; }
        public string CusBakC { get; set; }
        public string CusBakD { get; set; }
        public string CusBakE { get; set; }
    }
}
