//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCustomNeed
    {
        public int ID { get; set; }
        public string CustomName { get; set; }
        public string NeedContent { get; set; }
        public string NeedNow { get; set; }
        public string NeedProduct { get; set; }
        public string NeedTime { get; set; }
        public string NeedLike { get; set; }
        public string JingZhengDuiShou { get; set; }
        public string HeZuoYiYuan { get; set; }
        public string HeZuoJiLv { get; set; }
        public string NeedZhangAi { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFShare { get; set; }
        public string CusBakA { get; set; }
        public string CusBakB { get; set; }
        public string CusBakC { get; set; }
        public string CusBakD { get; set; }
        public string CusBakE { get; set; }
    }
}
