//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCarShiYong
    {
        public int ID { get; set; }
        public string CarName { get; set; }
        public string DriverUser { get; set; }
        public string YongCheUser { get; set; }
        public string YongCheBuMen { get; set; }
        public string QiShiTime { get; set; }
        public string JieShuTime { get; set; }
        public string MuDiDi { get; set; }
        public string LiCheng { get; set; }
        public string ShengQingUser { get; set; }
        public string DiaoDuUser { get; set; }
        public string ShengQingShiYou { get; set; }
        public string NowState { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
