//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCarLog
    {
        public int ID { get; set; }
        public string CarName { get; set; }
        public string LogDate { get; set; }
        public string JingBanUser { get; set; }
        public string DriverUser { get; set; }
        public string ChuCheDate { get; set; }
        public string StartNum { get; set; }
        public string EndNum { get; set; }
        public string XingShiTime { get; set; }
        public string ShiYou { get; set; }
        public string XingShiLiCheng { get; set; }
        public string YouHaoShu { get; set; }
        public string DaoDaAddress { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
