//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCarJiaYou
    {
        public int ID { get; set; }
        public string CarName { get; set; }
        public string JYDate { get; set; }
        public string JingBanUser { get; set; }
        public string DriverUser { get; set; }
        public string JiaYouAddress { get; set; }
        public string StartNum { get; set; }
        public string JiaYouNum { get; set; }
        public string YouFeiJinE { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
