//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCarShiYong
    {
        public int ID { get; set; }
        public string CarName { get; set; }
        public string DriverUser { get; set; }
        public string YongCheUser { get; set; }
        public string YongCheBuMen { get; set; }
        public string QiShiTime { get; set; }
        public string JieShuTime { get; set; }
        public string MuDiDi { get; set; }
        public string LiCheng { get; set; }
        public string ShengQingUser { get; set; }
        public string DiaoDuUser { get; set; }
        public string ShengQingShiYou { get; set; }
        public string NowState { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
