//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPCarBaoYang
    {
        public int ID { get; set; }
        public string CarName { get; set; }
        public string BYDate { get; set; }
        public string JingBanUser { get; set; }
        public string ZhuGuanUser { get; set; }
        public string BYQianLCBNum { get; set; }
        public string QiYouJinE { get; set; }
        public string BYJinE { get; set; }
        public string WeiXiuJinE { get; set; }
        public string OtherJinE { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
