//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPContract
    {
        public int ID { get; set; }
        public string HeTongName { get; set; }
        public string HeTongSerils { get; set; }
        public string HeTongLeiXing { get; set; }
        public string QianYueKeHu { get; set; }
        public string HeTongMiaoShu { get; set; }
        public string HeTongTiaoKuan { get; set; }
        public string HeTongContent { get; set; }
        public Nullable<System.DateTime> ShengXiaoDate { get; set; }
        public Nullable<System.DateTime> ZhongZhiDate { get; set; }
        public Nullable<System.DateTime> TiXingDate { get; set; }
        public string QianYueRenBuy { get; set; }
        public string QianYueRenSell { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public string FuJianList { get; set; }
        public string BackInfo { get; set; }
        public string NowState { get; set; }
        public Nullable<double> HTZJ { get; set; }
        public Nullable<double> YFFY { get; set; }
        public string SFJF { get; set; }
        public Nullable<double> SQFY { get; set; }
    }
}
