//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPDangAn
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string JuanKuName { get; set; }
        public string FileSerils { get; set; }
        public string FileTitle { get; set; }
        public string FaWenDanWei { get; set; }
        public string FaWenDate { get; set; }
        public string MiJi { get; set; }
        public string JingJi { get; set; }
        public string TypeStr { get; set; }
        public string GongWenType { get; set; }
        public string FilePage { get; set; }
        public string FuJianList { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFDel { get; set; }
    }
}
