//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPDanWeiInfo
    {
        public int ID { get; set; }
        public string DanWeiName { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string YouBian { get; set; }
        public string Address { get; set; }
        public string WebUrl { get; set; }
        public string Email { get; set; }
        public string KaiHuHang { get; set; }
        public string ZhangHao { get; set; }
    }
}
