//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPDangAn
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string JuanKuName { get; set; }
        public string FileSerils { get; set; }
        public string FileTitle { get; set; }
        public string FaWenDanWei { get; set; }
        public string FaWenDate { get; set; }
        public string MiJi { get; set; }
        public string JingJi { get; set; }
        public string TypeStr { get; set; }
        public string GongWenType { get; set; }
        public string FilePage { get; set; }
        public string FuJianList { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFDel { get; set; }
    }
}
