//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPDanWeiInfo
    {
        public int ID { get; set; }
        public string DanWeiName { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string YouBian { get; set; }
        public string Address { get; set; }
        public string WebUrl { get; set; }
        public string Email { get; set; }
        public string KaiHuHang { get; set; }
        public string ZhangHao { get; set; }
    }
}
