//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPGuDing
    {
        public int ID { get; set; }
        public string GDName { get; set; }
        public string GDSerils { get; set; }
        public string GDType { get; set; }
        public string SuoShuBuMen { get; set; }
        public string GDAllCount { get; set; }
        public string NowCount { get; set; }
        public string NianXian { get; set; }
        public string GDXingZhi { get; set; }
        public string QiYongDate { get; set; }
        public string BaoGuanUser { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
