//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPGuDing
    {
        public int ID { get; set; }
        public string GDName { get; set; }
        public string GDSerils { get; set; }
        public string GDType { get; set; }
        public string SuoShuBuMen { get; set; }
        public string GDAllCount { get; set; }
        public string NowCount { get; set; }
        public string NianXian { get; set; }
        public string GDXingZhi { get; set; }
        public string QiYongDate { get; set; }
        public string BaoGuanUser { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BackInfo { get; set; }
    }
}
