//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPHuiYuan
    {
        public int ID { get; set; }
        public string NameStr { get; set; }
        public string RuHuiDate { get; set; }
        public string JieShaoRen { get; set; }
        public string SexStr { get; set; }
        public string JiGuan { get; set; }
        public string JingJi { get; set; }
        public string ChuShengDate { get; set; }
        public string XueLi { get; set; }
        public string ZiLi { get; set; }
        public string GeXing { get; set; }
        public string AiHao { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string MobTel { get; set; }
        public string ZuiJiaTime { get; set; }
        public string ChangYong { get; set; }
        public string ZiXin { get; set; }
        public string JieLun { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
