//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPHuiYuan
    {
        public int ID { get; set; }
        public string NameStr { get; set; }
        public string RuHuiDate { get; set; }
        public string JieShaoRen { get; set; }
        public string SexStr { get; set; }
        public string JiGuan { get; set; }
        public string JingJi { get; set; }
        public string ChuShengDate { get; set; }
        public string XueLi { get; set; }
        public string ZiLi { get; set; }
        public string GeXing { get; set; }
        public string AiHao { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string MobTel { get; set; }
        public string ZuiJiaTime { get; set; }
        public string ChangYong { get; set; }
        public string ZiXin { get; set; }
        public string JieLun { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
