//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPJiangCheng
    {
        public int ID { get; set; }
        public string JCUser { get; set; }
        public string JiangChengQuFen { get; set; }
        public string JiangChengType { get; set; }
        public string ShouYuDanWei { get; set; }
        public string JiangChengDate { get; set; }
        public string JiangChengMingMu { get; set; }
        public string JiangChengYuanYin { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
