//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPJXDetails
    {
        public int ID { get; set; }
        public Nullable<int> JXID { get; set; }
        public Nullable<int> ItemsID { get; set; }
        public string UserName { get; set; }
        public string NumStr { get; set; }
    }
}
