//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPJiangCheng
    {
        public int ID { get; set; }
        public string JCUser { get; set; }
        public string JiangChengQuFen { get; set; }
        public string JiangChengType { get; set; }
        public string ShouYuDanWei { get; set; }
        public string JiangChengDate { get; set; }
        public string JiangChengMingMu { get; set; }
        public string JiangChengYuanYin { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
