//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPJianLi
    {
        public int ID { get; set; }
        public string YPName { get; set; }
        public string YPDate { get; set; }
        public string YPSex { get; set; }
        public string YPAge { get; set; }
        public string XueLi { get; set; }
        public string ZhuanYe { get; set; }
        public string YPZhiWei { get; set; }
        public string YPJieGuo { get; set; }
        public string BackInfo { get; set; }
        public string FuJianStr { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
