//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPKaoQin
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> GuiDingTime1 { get; set; }
        public Nullable<System.DateTime> DengJiTime1 { get; set; }
        public Nullable<System.DateTime> GuiDingTime2 { get; set; }
        public Nullable<System.DateTime> DengJiTime2 { get; set; }
        public Nullable<System.DateTime> GuiDingTime3 { get; set; }
        public Nullable<System.DateTime> DengJiTime3 { get; set; }
        public Nullable<System.DateTime> GuiDingTime4 { get; set; }
        public Nullable<System.DateTime> DengJiTime4 { get; set; }
        public Nullable<System.DateTime> GuiDingTime5 { get; set; }
        public Nullable<System.DateTime> DengJiTime5 { get; set; }
        public Nullable<System.DateTime> GuiDingTime6 { get; set; }
        public Nullable<System.DateTime> DengJiTime6 { get; set; }
        public Nullable<System.DateTime> KaoQinRiQi { get; set; }
    }
}
