//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPKaoQinSetting
    {
        public int ID { get; set; }
        public string GuiDingTime1 { get; set; }
        public string GuiDingTime2 { get; set; }
        public string GuiDingTime3 { get; set; }
        public string GuiDingTime4 { get; set; }
        public string GuiDingTime5 { get; set; }
        public string GuiDingTime6 { get; set; }
    }
}
