//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPKaoQin
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> GuiDingTime1 { get; set; }
        public Nullable<System.DateTime> DengJiTime1 { get; set; }
        public Nullable<System.DateTime> GuiDingTime2 { get; set; }
        public Nullable<System.DateTime> DengJiTime2 { get; set; }
        public Nullable<System.DateTime> GuiDingTime3 { get; set; }
        public Nullable<System.DateTime> DengJiTime3 { get; set; }
        public Nullable<System.DateTime> GuiDingTime4 { get; set; }
        public Nullable<System.DateTime> DengJiTime4 { get; set; }
        public Nullable<System.DateTime> GuiDingTime5 { get; set; }
        public Nullable<System.DateTime> DengJiTime5 { get; set; }
        public Nullable<System.DateTime> GuiDingTime6 { get; set; }
        public Nullable<System.DateTime> DengJiTime6 { get; set; }
        public Nullable<System.DateTime> KaoQinRiQi { get; set; }
    }
}
