//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPLinkMan
    {
        public int ID { get; set; }
        public string CustomName { get; set; }
        public string NameStr { get; set; }
        public string Sex { get; set; }
        public string BirthDay { get; set; }
        public string SuoChuJiaoSe { get; set; }
        public string ZhiWu { get; set; }
        public string PeiOu { get; set; }
        public string ZiNv { get; set; }
        public string DanWieDianHua { get; set; }
        public string DanWeiChuanZhen { get; set; }
        public string JiaTingZhuZhi { get; set; }
        public string JiaTingYouBian { get; set; }
        public string JiaTingDianHua { get; set; }
        public string ShouJi { get; set; }
        public string XiaoLingTong { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Msn { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFShare { get; set; }
        public string CusBakA { get; set; }
        public string CusBakB { get; set; }
        public string CusBakC { get; set; }
        public string CusBakD { get; set; }
        public string CusBakE { get; set; }
    }
}
