//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPLanEmailShou
    {
        public int ID { get; set; }
        public string ShouUser { get; set; }
        public string EmailTitle { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string EmailContent { get; set; }
        public string FuJian { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public string EmailState { get; set; }
        public string IFDel { get; set; }
    }
}
