//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPLiRun
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string SumJinE { get; set; }
        public string FeiYong { get; set; }
        public string ChengBen { get; set; }
        public string FangZu { get; set; }
        public string ShuiE { get; set; }
        public string GongZi { get; set; }
        public string TiCheng { get; set; }
        public string QiTa { get; set; }
        public string ShiJi { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
