//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPLiRun
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string SumJinE { get; set; }
        public string FeiYong { get; set; }
        public string ChengBen { get; set; }
        public string FangZu { get; set; }
        public string ShuiE { get; set; }
        public string GongZi { get; set; }
        public string TiCheng { get; set; }
        public string QiTa { get; set; }
        public string ShiJi { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
