//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPMeeting
    {
        public int ID { get; set; }
        public string MeetingTitle { get; set; }
        public string MeetingZhuTi { get; set; }
        public string MiaoShu { get; set; }
        public string ChuXiRen { get; set; }
        public string WangLuoHuiYiShiIP { get; set; }
        public string HuiYiZhuChi { get; set; }
        public Nullable<System.DateTime> KaiShiTime { get; set; }
        public Nullable<System.DateTime> JieShuTime { get; set; }
        public string HuiYiJiYao { get; set; }
        public string ZhuanXieRen { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string CurentOnline { get; set; }
        public string NowState { get; set; }
    }
}
