//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPMobile
    {
        public int ID { get; set; }
        public string FaSongUser { get; set; }
        public string ToUserList { get; set; }
        public string ContentStr { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
