//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPMianShi
    {
        public int ID { get; set; }
        public string MSName { get; set; }
        public string MSDate { get; set; }
        public string MSSex { get; set; }
        public string MSAge { get; set; }
        public string XueLi { get; set; }
        public string ZhuanYe { get; set; }
        public string MSZhiWei { get; set; }
        public string MSJieGuo { get; set; }
        public string BackInfo { get; set; }
        public string FuJianStr { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
