//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPMeeting
    {
        public int ID { get; set; }
        public string MeetingTitle { get; set; }
        public string MeetingZhuTi { get; set; }
        public string MiaoShu { get; set; }
        public string ChuXiRen { get; set; }
        public string WangLuoHuiYiShiIP { get; set; }
        public string HuiYiZhuChi { get; set; }
        public Nullable<System.DateTime> KaiShiTime { get; set; }
        public Nullable<System.DateTime> JieShuTime { get; set; }
        public string HuiYiJiYao { get; set; }
        public string ZhuanXieRen { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string CurentOnline { get; set; }
        public string NowState { get; set; }
    }
}
