//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPMianShi
    {
        public int ID { get; set; }
        public string MSName { get; set; }
        public string MSDate { get; set; }
        public string MSSex { get; set; }
        public string MSAge { get; set; }
        public string XueLi { get; set; }
        public string ZhuanYe { get; set; }
        public string MSZhiWei { get; set; }
        public string MSJieGuo { get; set; }
        public string BackInfo { get; set; }
        public string FuJianStr { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
