//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPNWorkToDo
    {
        public ERPNWorkToDo()
        {
            this.FundsRecord = new HashSet<FundsRecord>();
            this.ProjectRecord = new HashSet<ProjectRecord>();
            this.ProjectFile = new HashSet<ProjectFile>();
            this.ProjectRegistration = new HashSet<ProjectRegistration>();
            this.ProjectBidSection = new HashSet<ProjectBidSection>();
        }
    
        public int ID { get; set; }
        public string WorkName { get; set; }
        public string WenHao { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string FormContent { get; set; }
        public string FuJianList { get; set; }
        public string ShenPiYiJian { get; set; }
        public Nullable<int> JieDianID { get; set; }
        public string JieDianName { get; set; }
        public string ShenPiUserList { get; set; }
        public string OKUserList { get; set; }
        public string StateNow { get; set; }
        public Nullable<System.DateTime> LateTime { get; set; }
        public string BeiYong1 { get; set; }
        public string BeiYong2 { get; set; }
        public string ApplicationStatus { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string FormKeys { get; set; }
        public string FormValues { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsTemporary { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ProjectStatus { get; set; }
    
        public virtual ICollection<FundsRecord> FundsRecord { get; set; }
        public virtual ICollection<ProjectRecord> ProjectRecord { get; set; }
        public virtual ICollection<ProjectFile> ProjectFile { get; set; }
        public virtual ICollection<ProjectRegistration> ProjectRegistration { get; set; }
        public virtual ICollection<ProjectBidSection> ProjectBidSection { get; set; }
    }
}
