//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPNWorkFlowNode
    {
        public int ID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public string NodeSerils { get; set; }
        public string NodeName { get; set; }
        public string NodeAddr { get; set; }
        public string NextNode { get; set; }
        public string IFCanJump { get; set; }
        public string IFCanView { get; set; }
        public string IFCanEdit { get; set; }
        public string IFCanDel { get; set; }
        public Nullable<int> JieShuHours { get; set; }
        public string PSType { get; set; }
        public string SPType { get; set; }
        public string SPDefaultList { get; set; }
        public string CanWriteSet { get; set; }
        public string SecretSet { get; set; }
        public string ConditionSet { get; set; }
        public string NodeLeft { get; set; }
        public string NodeTop { get; set; }
    }
}
