//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPNWorkFlowToDoUser
    {
        public int ID { get; set; }
        public Nullable<int> ToDoID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public string ShenPiUserList { get; set; }
    }
}
