//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPNWorkFlowNode
    {
        public int ID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public string NodeSerils { get; set; }
        public string NodeName { get; set; }
        public string NodeAddr { get; set; }
        public string NextNode { get; set; }
        public string IFCanJump { get; set; }
        public string IFCanView { get; set; }
        public string IFCanEdit { get; set; }
        public string IFCanDel { get; set; }
        public Nullable<int> JieShuHours { get; set; }
        public string PSType { get; set; }
        public string SPType { get; set; }
        public string SPDefaultList { get; set; }
        public string CanWriteSet { get; set; }
        public string SecretSet { get; set; }
        public string ConditionSet { get; set; }
        public string NodeLeft { get; set; }
        public string NodeTop { get; set; }
    }
}
