//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPNForm
    {
        public int ID { get; set; }
        public string FormName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string UserListOK { get; set; }
        public string DepListOK { get; set; }
        public string JiaoSeListOK { get; set; }
        public string PaiXuStr { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string ContentStr { get; set; }
        public string ItemsList { get; set; }
        public string IFOK { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string ModifiedPerson { get; set; }
        public string ApprovalFlowDescription { get; set; }
        public string FormType { get; set; }
    }
}
