//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPNFormType
    {
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string PaiXuStr { get; set; }
        public string BackInfo { get; set; }
    }
}
