//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPOffice
    {
        public int ID { get; set; }
        public string OfficeName { get; set; }
        public string MiaoShu { get; set; }
        public string FuJianStr { get; set; }
        public string TypeStr { get; set; }
        public string Serils { get; set; }
        public string DanWei { get; set; }
        public string DanJia { get; set; }
        public string GongYingShang { get; set; }
        public string MinNum { get; set; }
        public string MaxNum { get; set; }
        public string NowNum { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
