//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPProduct
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ProductSerils { get; set; }
        public string GongYingShang { get; set; }
        public string ProductType { get; set; }
        public string XingHao { get; set; }
        public string DanWei { get; set; }
        public string ChengBen { get; set; }
        public string ChuShou { get; set; }
        public Nullable<decimal> RuKuSum { get; set; }
        public Nullable<decimal> ChuKuSum { get; set; }
        public Nullable<decimal> NowKuCun { get; set; }
        public Nullable<decimal> KuCunBaoJing { get; set; }
        public string CunChuWeiZhi { get; set; }
        public string ChanPinMiaoShu { get; set; }
        public string BackInfo { get; set; }
        public string ProductSize { get; set; }
        public string Performance { get; set; }
        public string Coating { get; set; }
        public string SurfaceTreatment { get; set; }
        public string MagnetizingDirection { get; set; }
        public string Tolerance { get; set; }
        public Nullable<int> IsContainingTax { get; set; }
    }
}
