//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPProduct
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ProductSerils { get; set; }
        public string GongYingShang { get; set; }
        public string ProductType { get; set; }
        public string XingHao { get; set; }
        public string DanWei { get; set; }
        public string ChengBen { get; set; }
        public string ChuShou { get; set; }
        public Nullable<decimal> RuKuSum { get; set; }
        public Nullable<decimal> ChuKuSum { get; set; }
        public Nullable<decimal> NowKuCun { get; set; }
        public Nullable<decimal> KuCunBaoJing { get; set; }
        public string CunChuWeiZhi { get; set; }
        public string ChanPinMiaoShu { get; set; }
        public string BackInfo { get; set; }
        public string ProductSize { get; set; }
        public string Performance { get; set; }
        public string Coating { get; set; }
        public string SurfaceTreatment { get; set; }
        public string MagnetizingDirection { get; set; }
        public string Tolerance { get; set; }
        public Nullable<int> IsContainingTax { get; set; }
    }
}
