//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPProject
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string SuoShuKeHu { get; set; }
        public string YuJiChengJiaoRiQi { get; set; }
        public string TiXingDate { get; set; }
        public string FuZeRen { get; set; }
        public string XiangMuJinE { get; set; }
        public string XiangMuYuSuan { get; set; }
        public string XiangMuDaXiao { get; set; }
        public string PeiHeRenList { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string HeTongAndFuJian { get; set; }
        public string BackInfo { get; set; }
    }
}
