//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPPinShen
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string PingShenTime { get; set; }
        public string PingShenJieGuo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string BachInfo { get; set; }
    }
}
