//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPProject
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string SuoShuKeHu { get; set; }
        public string YuJiChengJiaoRiQi { get; set; }
        public string TiXingDate { get; set; }
        public string FuZeRen { get; set; }
        public string XiangMuJinE { get; set; }
        public string XiangMuYuSuan { get; set; }
        public string XiangMuDaXiao { get; set; }
        public string PeiHeRenList { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string HeTongAndFuJian { get; set; }
        public string BackInfo { get; set; }
    }
}
