//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPRiZhi
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string DoSomething { get; set; }
        public string IpStr { get; set; }
        public string NotificationContent { get; set; }
        public string FkFormName { get; set; }
        public string FKAction { get; set; }
        public string FKApplicationID { get; set; }
        public string ModuleName { get; set; }
    }
}
