//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPRiZhi
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string DoSomething { get; set; }
        public string IpStr { get; set; }
        public string NotificationContent { get; set; }
        public string FkFormName { get; set; }
        public string FKAction { get; set; }
        public string FKApplicationID { get; set; }
        public string ModuleName { get; set; }
    }
}
