//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPRenShiHeTong
    {
        public int ID { get; set; }
        public string HeTongUser { get; set; }
        public string NowState { get; set; }
        public string Serils { get; set; }
        public string TypeStr { get; set; }
        public string JingYe { get; set; }
        public string BaoMiXieYi { get; set; }
        public string QianYueDate { get; set; }
        public string ManYueDate { get; set; }
        public string JianZhengJiGuan { get; set; }
        public string JianZhengDate { get; set; }
        public string WeiYueZeRen { get; set; }
        public string BackInfo { get; set; }
        public string FuJianList { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
