//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPRenShiHeTong
    {
        public int ID { get; set; }
        public string HeTongUser { get; set; }
        public string NowState { get; set; }
        public string Serils { get; set; }
        public string TypeStr { get; set; }
        public string JingYe { get; set; }
        public string BaoMiXieYi { get; set; }
        public string QianYueDate { get; set; }
        public string ManYueDate { get; set; }
        public string JianZhengJiGuan { get; set; }
        public string JianZhengDate { get; set; }
        public string WeiYueZeRen { get; set; }
        public string BackInfo { get; set; }
        public string FuJianList { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
