//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPSongYang
    {
        public int ID { get; set; }
        public string CustomName { get; set; }
        public string SongYangLiaoHao { get; set; }
        public string SongYangType { get; set; }
        public string SongYangShuLiang { get; set; }
        public string SongYangDanJia { get; set; }
        public string SongYangJinE { get; set; }
        public string SongYangResult { get; set; }
        public string SongYangTime { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string IFShare { get; set; }
        public string CusBakA { get; set; }
        public string CusBakB { get; set; }
        public string CusBakC { get; set; }
        public string CusBakD { get; set; }
        public string CusBakE { get; set; }
    }
}
