//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPSupplys
    {
        public int ID { get; set; }
        public string SupplysName { get; set; }
        public string Serils { get; set; }
        public string JianCheng { get; set; }
        public string DianHua { get; set; }
        public string MobTel { get; set; }
        public string ChuanZhen { get; set; }
        public string URLStr { get; set; }
        public string EmailStr { get; set; }
        public string DiQu { get; set; }
        public string YouBian { get; set; }
        public string Address { get; set; }
        public string KaiHuHang { get; set; }
        public string ZhangHao { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
