//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPShiShi
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string ShiShiTime { get; set; }
        public string ShiShiRen { get; set; }
        public string ShiShiContent { get; set; }
        public string WanGongLiang { get; set; }
        public string PingJia { get; set; }
        public string XiaoJie { get; set; }
        public string WenTi { get; set; }
        public string YuJiJieJueRiQi { get; set; }
        public string WenTiJieDa { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
