//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPSupplyLink
    {
        public int ID { get; set; }
        public string SupplysName { get; set; }
        public string LinkManName { get; set; }
        public string ZhiWei { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> ShengRi { get; set; }
        public string AiHao { get; set; }
        public string IFFirstLink { get; set; }
        public string YouBian { get; set; }
        public string DiZhi { get; set; }
        public string JobTel { get; set; }
        public string JiaTingTel { get; set; }
        public string MobTel { get; set; }
        public string EmailStr { get; set; }
        public string QQorMsn { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
