//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPSupplys
    {
        public int ID { get; set; }
        public string SupplysName { get; set; }
        public string Serils { get; set; }
        public string JianCheng { get; set; }
        public string DianHua { get; set; }
        public string MobTel { get; set; }
        public string ChuanZhen { get; set; }
        public string URLStr { get; set; }
        public string EmailStr { get; set; }
        public string DiQu { get; set; }
        public string YouBian { get; set; }
        public string Address { get; set; }
        public string KaiHuHang { get; set; }
        public string ZhangHao { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
