//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPSheBei
    {
        public int ID { get; set; }
        public string SheBeiName { get; set; }
        public string YuanBianHao { get; set; }
        public string CaiWuBianHao { get; set; }
        public string JiBuBianHao { get; set; }
        public string SheBeiLeiBie { get; set; }
        public string XingHao { get; set; }
        public string XiangMu { get; set; }
        public string ChuChangBianHao { get; set; }
        public string ShiYongBuMen { get; set; }
        public string ShengChanChangJia { get; set; }
        public string DanWei { get; set; }
        public string DanJia { get; set; }
        public string SuYuanFangShi { get; set; }
        public string SuYaunDanWei { get; set; }
        public string SuYuanZhouQi { get; set; }
        public string ShangCiSuYuanDate { get; set; }
        public string JiHuaSuYaunDate { get; set; }
        public string ZhengShuBianHao { get; set; }
        public string CeLiangFanWei { get; set; }
        public string BuQueDingDu { get; set; }
        public string ShiYongCeLiangFanWei { get; set; }
        public string JingDu { get; set; }
        public string JieGuoPingJia { get; set; }
        public string PingJiaUser { get; set; }
        public string QianZiDate { get; set; }
        public string ZhengGai { get; set; }
        public string ChuCiSuYuanDate { get; set; }
        public string QiYongDate { get; set; }
        public string CunFangAddr { get; set; }
        public string GuanLiUser { get; set; }
        public string JiFei { get; set; }
        public string ZhuangTai { get; set; }
        public string BeiZhu { get; set; }
        public string HeDuiUser { get; set; }
        public string TiXingDate { get; set; }
        public string TiXingUser { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
