//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPShiShi
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string ShiShiTime { get; set; }
        public string ShiShiRen { get; set; }
        public string ShiShiContent { get; set; }
        public string WanGongLiang { get; set; }
        public string PingJia { get; set; }
        public string XiaoJie { get; set; }
        public string WenTi { get; set; }
        public string YuJiJieJueRiQi { get; set; }
        public string WenTiJieDa { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
