//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPShouKuan
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSerils { get; set; }
        public string JieDuanName { get; set; }
        public string ShouKuanE { get; set; }
        public string FaPiaoHao { get; set; }
        public string ShouKuanDate { get; set; }
        public string DaoKuanDate { get; set; }
        public string ShengYuE { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
