//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTiKuShiJuanSet
    {
        public int ID { get; set; }
        public Nullable<int> DanXuanNum { get; set; }
        public Nullable<int> DuoXuanNum { get; set; }
        public Nullable<int> PanDuanNum { get; set; }
        public Nullable<int> TianKongNum { get; set; }
        public Nullable<int> JianDaNum { get; set; }
        public Nullable<int> ShiJuanID { get; set; }
        public Nullable<int> TiKuTypeID { get; set; }
    }
}
