//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTiKuShiJuan
    {
        public int ID { get; set; }
        public string ShiJuanTitle { get; set; }
        public string IFSuiJiChuTi { get; set; }
        public string FenLeiShunXu { get; set; }
        public Nullable<int> KaoShiXianShi { get; set; }
        public string PanDuanTiList { get; set; }
        public string DanXuanTiList { get; set; }
        public string DuoXuanTiList { get; set; }
        public string TianKongTiList { get; set; }
        public string JianDaTiList { get; set; }
        public Nullable<decimal> PanDuanFenShu { get; set; }
        public Nullable<decimal> DanXuanFenShu { get; set; }
        public Nullable<decimal> DuoXuanFenShu { get; set; }
        public Nullable<decimal> TianKongFenShu { get; set; }
        public Nullable<decimal> JianDaFenShu { get; set; }
        public string BackInfo { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
