//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTiKu
    {
        public int ID { get; set; }
        public string TitleStr { get; set; }
        public string ItemsA { get; set; }
        public string ItemsB { get; set; }
        public string ItemsC { get; set; }
        public string ItemsD { get; set; }
        public string ItemsE { get; set; }
        public string ItemsF { get; set; }
        public string ItemsG { get; set; }
        public string ItemsH { get; set; }
        public string AnswerStr { get; set; }
        public Nullable<int> TiKuID { get; set; }
        public string FenLeiStr { get; set; }
    }
}
