//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTiKuShiJuanSet
    {
        public int ID { get; set; }
        public Nullable<int> DanXuanNum { get; set; }
        public Nullable<int> DuoXuanNum { get; set; }
        public Nullable<int> PanDuanNum { get; set; }
        public Nullable<int> TianKongNum { get; set; }
        public Nullable<int> JianDaNum { get; set; }
        public Nullable<int> ShiJuanID { get; set; }
        public Nullable<int> TiKuTypeID { get; set; }
    }
}
