//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTreeList
    {
        public int ID { get; set; }
        public string TextStr { get; set; }
        public string ImageUrlStr { get; set; }
        public string ValueStr { get; set; }
        public string NavigateUrlStr { get; set; }
        public string Target { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string QuanXianList { get; set; }
        public Nullable<int> PaiXuStr { get; set; }
        public string ParentClass { get; set; }
    }
}
