//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTreeList
    {
        public int ID { get; set; }
        public string TextStr { get; set; }
        public string ImageUrlStr { get; set; }
        public string ValueStr { get; set; }
        public string NavigateUrlStr { get; set; }
        public string Target { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string QuanXianList { get; set; }
        public Nullable<int> PaiXuStr { get; set; }
        public string ParentClass { get; set; }
    }
}
