//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTaskFP
    {
        public int ID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskContent { get; set; }
        public string FromUser { get; set; }
        public string ToUserList { get; set; }
        public string XinXiGouTong { get; set; }
        public Nullable<decimal> JinDu { get; set; }
        public string WanCheng { get; set; }
        public string NowState { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string SFFK { get; set; }
        public Nullable<System.DateTime> FKSJ { get; set; }
    }
}
