//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTongXunLu
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string IfShare { get; set; }
        public string TypeStr { get; set; }
        public string FenZu { get; set; }
        public string NameStr { get; set; }
        public string Sex { get; set; }
        public string BirthDay { get; set; }
        public string NiCheng { get; set; }
        public string ZhiWu { get; set; }
        public string PeiOu { get; set; }
        public string ZiNv { get; set; }
        public string DanWeiMingCheng { get; set; }
        public string DanWeiDiZhi { get; set; }
        public string DanWeiYouBian { get; set; }
        public string DanWieDianHua { get; set; }
        public string DanWeiChuanZhen { get; set; }
        public string JiaTingZhuZhi { get; set; }
        public string JiaTingYouBian { get; set; }
        public string JiaTingDianHua { get; set; }
        public string ShouJi { get; set; }
        public string XiaoLingTong { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Msn { get; set; }
        public string BackInfo { get; set; }
    }
}
