//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTiKuKaoShiJieGuo
    {
        public int ID { get; set; }
        public Nullable<int> KaoShiID { get; set; }
        public Nullable<int> TiMuID { get; set; }
        public string DaAn { get; set; }
        public string UserDaAn { get; set; }
        public Nullable<decimal> DeFen { get; set; }
    }
}
