//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTiKu
    {
        public int ID { get; set; }
        public string TitleStr { get; set; }
        public string ItemsA { get; set; }
        public string ItemsB { get; set; }
        public string ItemsC { get; set; }
        public string ItemsD { get; set; }
        public string ItemsE { get; set; }
        public string ItemsF { get; set; }
        public string ItemsG { get; set; }
        public string ItemsH { get; set; }
        public string AnswerStr { get; set; }
        public Nullable<int> TiKuID { get; set; }
        public string FenLeiStr { get; set; }
    }
}
