//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPTelFile
    {
        public int ID { get; set; }
        public string TitleStr { get; set; }
        public string FromUser { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string FileType { get; set; }
        public string ToUser { get; set; }
        public string YiJieShouRen { get; set; }
        public string ContentStr { get; set; }
        public string FuJianStr { get; set; }
        public string ChuanYueYiJian { get; set; }
        public string QianShouHouIDList { get; set; }
        public string ChuanYueHouIDList1 { get; set; }
        public string Zihao { get; set; }
    }
}
