//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string TrueName { get; set; }
        public string Serils { get; set; }
        public string Department { get; set; }
        public string JiaoSe { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public string ZhiWei { get; set; }
        public string ZaiGang { get; set; }
        public string EmailStr { get; set; }
        public string IfLogin { get; set; }
        public string Sex { get; set; }
        public string BackInfo { get; set; }
        public string BirthDay { get; set; }
        public string MingZu { get; set; }
        public string SFZSerils { get; set; }
        public string HunYing { get; set; }
        public string ZhengZhiMianMao { get; set; }
        public string JiGuan { get; set; }
        public string HuKou { get; set; }
        public string XueLi { get; set; }
        public string ZhiCheng { get; set; }
        public string BiYeYuanXiao { get; set; }
        public string ZhuanYe { get; set; }
        public string CanJiaGongZuoTime { get; set; }
        public string JiaRuBenDanWeiTime { get; set; }
        public string JiaTingDianHua { get; set; }
        public string JiaTingAddress { get; set; }
        public string GangWeiBianDong { get; set; }
        public string JiaoYueBeiJing { get; set; }
        public string GongZuoJianLi { get; set; }
        public string SheHuiGuanXi { get; set; }
        public string JiangChengJiLu { get; set; }
        public string ZhiWuQingKuang { get; set; }
        public string PeiXunJiLu { get; set; }
        public string DanBaoJiLu { get; set; }
        public string NaoDongHeTong { get; set; }
        public string SheBaoJiaoNa { get; set; }
        public string TiJianJiLu { get; set; }
        public string BeiZhuStr { get; set; }
        public string FuJian { get; set; }
        public string POP3UserName { get; set; }
        public string POP3UserPwd { get; set; }
        public string POP3Server { get; set; }
        public string POP3Port { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPUserPwd { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPFromEmail { get; set; }
        public string TiXingTime { get; set; }
        public string IfTiXing { get; set; }
        public string DaoHangList { get; set; }
        public string xKeGuanDep { get; set; }
        public string XiaShuUser { get; set; }
    }
}
