//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPWorkPlan
    {
        public int ID { get; set; }
        public string TitleStr { get; set; }
        public string ContentStr { get; set; }
        public string FuJianStr { get; set; }
        public string UserName { get; set; }
        public string CanLookUser { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
    }
}
