//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundsRecord
    {
        public FundsRecord()
        {
            this.TravelFundsDetail = new HashSet<TravelFundsDetail>();
        }
    
        public int ID { get; set; }
        public int ApplicationId { get; set; }
        public int WorkflowId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string ProjectName { get; set; }
        public int CountOfBill { get; set; }
        public double UnitPrice { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<bool> IsIncome { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<System.DateTime> LastPrintTime { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeStr { get; set; }
        public string FuJianList { get; set; }
        public string ShenPiYiJian { get; set; }
        public Nullable<int> JieDianID { get; set; }
        public string JieDianName { get; set; }
        public string ShenPiUserList { get; set; }
        public string OKUserList { get; set; }
        public string StateNow { get; set; }
        public Nullable<System.DateTime> LateTime { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsTemporary { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ERPNWorkFlow ERPNWorkFlow { get; set; }
        public virtual ERPNWorkToDo ERPNWorkToDo { get; set; }
        public virtual ICollection<TravelFundsDetail> TravelFundsDetail { get; set; }
    }
}
