//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBidSection
    {
        public int ID { get; set; }
        public int ApplicationId { get; set; }
        public string SectionNumber { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual ERPNWorkToDo ERPNWorkToDo { get; set; }
    }
}
