//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRegistration
    {
        public int ID { get; set; }
        public int ApplicationId { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string BidSection { get; set; }
        public bool IsSubmitRegistrationFee { get; set; }
        public long RegistrationFee { get; set; }
        public bool IsSubmitBidBondFee { get; set; }
        public long BidBondFee { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string OperatorName { get; set; }
        public string OperatorId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual ERPNWorkToDo ERPNWorkToDo { get; set; }
    }
}
