//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFile
    {
        public int ID { get; set; }
        public int ApplicationId { get; set; }
        public int FileType { get; set; }
        public string FileName { get; set; }
        public string FileAddress { get; set; }
        public string FileSize { get; set; }
        public string Remark { get; set; }
        public string OperatorName { get; set; }
        public string OperatorId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public int SectionId { get; set; }
    
        public virtual ERPNWorkToDo ERPNWorkToDo { get; set; }
    }
}
