//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelFundsDetail
    {
        public int ID { get; set; }
        public Nullable<int> FundsRecordId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string Transportation { get; set; }
        public Nullable<double> TransportationFee { get; set; }
        public Nullable<double> HotelFee { get; set; }
        public Nullable<double> OtherFee { get; set; }
        public string OtherFeeComment { get; set; }
    
        public virtual FundsRecord FundsRecord { get; set; }
    }
}
