//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearch.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelFundsDetail
    {
        public int ID { get; set; }
        public Nullable<int> FundsRecordId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string Transportation { get; set; }
        public Nullable<double> TransportationFee { get; set; }
        public Nullable<double> HotelFee { get; set; }
        public Nullable<double> OtherFee { get; set; }
        public string OtherFeeComment { get; set; }
    
        public virtual FundsRecord FundsRecord { get; set; }
    }
}
